apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-nofu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-nofu
    app.kubernetes.io/part-of: ci10t-777-0065-app
  name: devfile-sample-nofu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-nofu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-nofu
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0065-tenant/ci10t-777-0065-app/devfile-sample-nofu@sha256:b10e41e820406df1a1b8def2848ace1eb44b9dc0783eac91e185a0da3c0695aa
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
